language: node_js
node_js:
  - "5"
services:
  - mongodb
  - redis
before_script:
  - cp config/server/config_sample.json config/server/config.json
script: "npm run-script test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo $CODACY_PROJECT_TOKEN"
